### ISSUE TITLE
How about for Banner Ad?

### ISSUE THREAD

**Issue by ssatz** [mohammedmanssour/fuse-AdMobInterstitialAds#1]
Hi,

Thanks for the wonderful package!  
Is it possible to add Banner ad?

Best Regards,
Satz

**Comment by mohammedmanssour** [comment]
Hi!

Banner Ads can be added using [**Fuse.Firebase**](https://github.com/fuse-compound/Fuse.Firebase) package. I only  made this package because there were no packages existed that provide same functionality.

Best Regards,
Mohammed
